Add tool installations and update project setup
Added new tools (assetfinder, grepcidr, gowitness, httprobe, jq, sublist3r, subfinder) to the install script. Refactored the installation process for RustScan and added support for installing Dalfox and Waybackurls. Updated `.gitignore` and removed unused section from the README.

diff --git a/install_tools b/install_tools
--- a/install_tools
+++ b/install_tools
@@ -5,8 +5,15 @@ sudo apt update
 
 ## Install tools
 tools_list=(
+	assetfinder
 	docker.io
+	grepcidr
+	gowitness
+	httprobe
+	jq
 	peass
+	sublist3r
+	subfinder
 )
 
 for tool in "${tools_list[@]}"; do
@@ -38,30 +45,75 @@ cp /usr/share/peass/winpeas/winPEASx64.exe "$HOME/Pentesting/scripts/windows/"
 cp /usr/share/peass/winpeas/winPEASx86.exe "$HOME/Pentesting/scripts/windows/"
 
 ## Download other tools on github
-# Download latest rustscan
-LATEST_RELEASE_URL=$(curl -s "https://api.github.com/repos/RustScan/RustScan/releases/latest" | grep -m 1 "browser_download_url" | cut -d '"' -f 4)
+install_rustscan() {
+	# Download latest rustscan
+	LATEST_RUSTSCAN_RELEASE_URL=$(curl -s "https://api.github.com/repos/RustScan/RustScan/releases/latest" | grep -m 1 "browser_download_url" | cut -d '"' -f 4)
 
-if [[ -z "$LATEST_RELEASE_URL" ]]; then
-    echo "Error: Download-Link was not found!"
-    exit 1
-fi
+	if [[ -z "$LATEST_RUSTSCAN_RELEASE_URL" ]]; then
+		echo "Error: Download-Link was not found!"
+		exit 1
+	fi
 
-if command -v wget &> /dev/null; then
-	wget -q --show-progress "$LATEST_RELEASE_URL"
-elif command -v curl &> /dev/null; then
-	curl -L --progress-bar -O "$LATEST_RELEASE_URL"
-else
-	echo "Error. Could not download rustscan."
-	exit 1
-fi
+	if command -v wget &> /dev/null; then
+		wget -q --show-progress "$LATEST_RUSTSCAN_RELEASE_URL"
+	elif command -v curl &> /dev/null; then
+		curl -L --progress-bar -O "$LATEST_RUSTSCAN_RELEASE_URL"
+	else
+		echo "Error. Could not download rustscan."
+		exit 1
+	fi
 
-tools_to_copy=(
-	rustscan
-	network-scanner
-)
+	sudo cp rustscan /usr/bin/
+}
 
-# Copy the binaries in /user/bin directory
-for tool in "${tools_to_copy[@]}"; do
-	sudo cp rustscan /usr/bin/"$tool"
-	sudo chmod +x /usr/bin/"$tool"
-done
+install_dalfox() {
+	# Download latest dalfox
+	LATEST_DALFOX_RELEASE_URL=$(curl -s "https://api.github.com/repos/hahwul/dalfox/releases/latest" | grep "browser_download_url" | grep "linux_amd64.tar.gz" | cut -d '"' -f 4)
+	FILE_NAME=$(basename "$LATEST_DALFOX_RELEASE_URL")
+
+	if [[ -z "$LATEST_DALFOX_RELEASE_URL" ]]; then
+		echo "Error: Download-Link was not found!"
+		exit 1
+	fi
+
+	if command -v wget &> /dev/null; then
+		wget -q --show-progress "$LATEST_DALFOX_RELEASE_URL"
+	elif command -v curl &> /dev/null; then
+		curl -L --progress-bar -O "$LATEST_DALFOX_RELEASE_URL"
+	else
+		echo "Error. Could not download dalfox."
+		exit 1
+	fi
+
+	tar -xzf "$FILE_NAME"
+	sudo cp dalfox /usr/bin
+	rm "$FILE_NAME" dalfox LICENSE.txt README.md
+}
+
+install_waybackurls() {
+	# Download latest dalfox
+	LATEST_WAYBACKURLS_RELEASE_URL=$(curl -s "https://api.github.com/repos/tomnomnom/waybackurls/releases/latest" | grep "browser_download_url" | grep "linux-amd64" | grep ".tgz" | cut -d '"' -f 4)
+	FILE_NAME=$(basename "$LATEST_WAYBACKURLS_RELEASE_URL")
+
+	if [[ -z "$LATEST_WAYBACKURLS_RELEASE_URL" ]]; then
+		echo "Error: Download-Link was not found!"
+		exit 1
+	fi
+
+	if command -v wget &> /dev/null; then
+		wget -q --show-progress "$LATEST_WAYBACKURLS_RELEASE_URL"
+	elif command -v curl &> /dev/null; then
+		curl -L --progress-bar -O "$LATEST_WAYBACKURLS_RELEASE_URL"
+	else
+		echo "Error. Could not download dalfox."
+		exit 1
+	fi
+
+	tar -xzf "$FILE_NAME"
+	sudo cp waybackurls /usr/bin
+	rm "$FILE_NAME" waybackurls
+}
+
+install_rustscan
+install_dalfox
+install_waybackurls
